// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjISzicDc9P1tzvxTgU6hmxYOpqpSHoVY',
    appId: '1:668938177272:web:088dc980f78c00171fc90d',
    messagingSenderId: '668938177272',
    projectId: 'saopauloempontos',
    authDomain: 'saopauloempontos.firebaseapp.com',
    storageBucket: 'saopauloempontos.appspot.com',
    measurementId: 'G-18MSSLH1FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCanZYFLQSPhWRv4dAjAA5BTRmKKQ5RQLY',
    appId: '1:668938177272:android:7f45fd938b2c95561fc90d',
    messagingSenderId: '668938177272',
    projectId: 'saopauloempontos',
    storageBucket: 'saopauloempontos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWlpUdVzD2FOdGm8DYthV02inUtWPcr94',
    appId: '1:668938177272:ios:fead7b8a10df71f01fc90d',
    messagingSenderId: '668938177272',
    projectId: 'saopauloempontos',
    storageBucket: 'saopauloempontos.appspot.com',
    iosBundleId: 'com.example.spPontos',
  );
}
